import type { DonorCell, PracticeCase } from "./types";
import { inferCellZygosity } from "./zygosity";

const cell = (
  label: string,
  antigens: DonorCell["antigens"],
): DonorCell => ({
  id: `cell-${label}`,
  label,
  antigens,
  zygosity: inferCellZygosity(antigens),
});

const baseNegative = {
  D: "negative",
  C: "negative",
  E: "negative",
  c: "negative",
  e: "negative",
  M: "negative",
  N: "negative",
  S: "negative",
  s: "negative",
  P1: "negative",
  Lea: "negative",
  Leb: "negative",
  K: "negative",
  k: "positive",
  Cw: "negative",
  V: "negative",
  Kpa: "negative",
  Kpb: "negative",
  Fya: "negative",
  Fyb: "negative",
  Jka: "negative",
  Jkb: "negative",
  Jsa: "negative",
  Jsb: "negative",
  Lua: "negative",
  Lub: "negative",
} as const;

const autoControl: DonorCell = {
  id: "auto",
  label: "Auto",
  isAutoControl: true,
  antigens: {},
  zygosity: {},
};

export const practiceCases: PracticeCase[] = [
  {
    id: "case-anti-e",
    title: "Case 1",
    summary: "Synthetic panel with IAT reactivity consistent with anti-E.",
    targetAntibodyId: "anti-E",
    cells: [
      cell(
        "1",
        {
          ...baseNegative,
          D: "positive",
          C: "positive",
          e: "positive",
          M: "positive",
          S: "positive",
          Cw: "positive",
          Kpb: "positive",
          Lua: "positive",
          k: "positive",
          Fya: "positive",
          Jka: "positive",
        },
      ),
      cell(
        "2",
        {
          ...baseNegative,
          D: "positive",
          C: "positive",
          e: "positive",
          N: "positive",
          s: "positive",
          V: "positive",
          Kpa: "positive",
          Jsb: "positive",
          P1: "positive",
          k: "positive",
          Fyb: "positive",
          Jkb: "positive",
        },
      ),
      cell(
        "3",
        {
          ...baseNegative,
          D: "positive",
          E: "positive",
          c: "positive",
          M: "positive",
          N: "positive",
          Cw: "positive",
          Jsa: "positive",
          K: "positive",
          k: "positive",
          Jka: "positive",
        },
      ),
      cell(
        "4",
        {
          ...baseNegative,
          E: "positive",
          c: "positive",
          e: "positive",
          S: "positive",
          s: "positive",
          Kpb: "positive",
          Lub: "positive",
          Lea: "positive",
          k: "positive",
          Fya: "positive",
        },
      ),
      cell(
        "5",
        {
          ...baseNegative,
          c: "positive",
          e: "positive",
          M: "positive",
          P1: "positive",
          V: "positive",
          Lua: "positive",
          Leb: "positive",
          k: "positive",
          Fyb: "positive",
          Jkb: "positive",
        },
      ),
      cell(
        "6",
        {
          ...baseNegative,
          E: "positive",
          c: "positive",
          e: "positive",
          N: "positive",
          S: "positive",
          Cw: "positive",
          Kpa: "positive",
          Jsa: "positive",
          k: "positive",
          Fya: "positive",
          Jka: "positive",
          Jkb: "positive",
        },
      ),
      cell(
        "7",
        {
          ...baseNegative,
          c: "positive",
          e: "positive",
          M: "positive",
          s: "positive",
          V: "positive",
          Jsb: "positive",
          Lea: "positive",
          k: "positive",
          Fya: "positive",
          Jka: "positive",
        },
      ),
      cell(
        "8",
        {
          ...baseNegative,
          c: "positive",
          e: "positive",
          N: "positive",
          S: "positive",
          Kpb: "positive",
          Lub: "positive",
          P1: "positive",
          k: "positive",
          Fyb: "positive",
          Jkb: "positive",
        },
      ),
      cell(
        "9",
        {
          ...baseNegative,
          c: "positive",
          e: "positive",
          M: "positive",
          N: "positive",
          s: "positive",
          Cw: "positive",
          Kpa: "positive",
          Jsa: "positive",
          K: "positive",
          k: "positive",
          Fya: "positive",
          Fyb: "positive",
        },
      ),
      cell(
        "10",
        {
          ...baseNegative,
          C: "positive",
          c: "positive",
          e: "positive",
          S: "positive",
          s: "positive",
          V: "positive",
          Lua: "positive",
          P1: "positive",
          Leb: "positive",
          k: "positive",
          Jka: "positive",
        },
      ),
      cell(
        "11",
        {
          ...baseNegative,
          D: "positive",
          E: "positive",
          c: "positive",
          M: "positive",
          N: "positive",
          Cw: "positive",
          Jsb: "positive",
          Lea: "positive",
          k: "positive",
          Fyb: "positive",
          Jkb: "positive",
        },
      ),
      autoControl,
    ],
    reactions: {
      "cell-1": "0",
      "cell-2": "0",
      "cell-3": "2+",
      "cell-4": "2+",
      "cell-5": "0",
      "cell-6": "2+",
      "cell-7": "0",
      "cell-8": "0",
      "cell-9": "0",
      "cell-10": "0",
      "cell-11": "2+",
      auto: "0",
    },
  },
  {
    id: "case-anti-fya",
    title: "Case 2",
    summary: "Synthetic panel with IAT reactivity consistent with anti-Fya.",
    targetAntibodyId: "anti-Fya",
    cells: [
      cell(
        "1",
        {
          ...baseNegative,
          D: "positive",
          C: "positive",
          e: "positive",
          M: "positive",
          S: "positive",
          Cw: "positive",
          Kpb: "positive",
          Lua: "positive",
          k: "positive",
          Fya: "positive",
          Fyb: "positive",
          Jka: "positive",
        },
      ),
      cell(
        "2",
        {
          ...baseNegative,
          D: "positive",
          C: "positive",
          e: "positive",
          N: "positive",
          s: "positive",
          V: "positive",
          Kpa: "positive",
          Jsb: "positive",
          P1: "positive",
          k: "positive",
          Fyb: "positive",
          Jkb: "positive",
        },
      ),
      cell(
        "3",
        {
          ...baseNegative,
          D: "positive",
          E: "positive",
          c: "positive",
          M: "positive",
          N: "positive",
          Cw: "positive",
          Jsa: "positive",
          K: "positive",
          k: "positive",
          Jka: "positive",
        },
      ),
      cell(
        "4",
        {
          ...baseNegative,
          E: "positive",
          c: "positive",
          e: "positive",
          S: "positive",
          s: "positive",
          Kpb: "positive",
          Lub: "positive",
          Lea: "positive",
          k: "positive",
          Fya: "positive",
        },
      ),
      cell(
        "5",
        {
          ...baseNegative,
          c: "positive",
          e: "positive",
          M: "positive",
          P1: "positive",
          V: "positive",
          Lua: "positive",
          Leb: "positive",
          k: "positive",
          Fyb: "positive",
          Jkb: "positive",
        },
      ),
      cell(
        "6",
        {
          ...baseNegative,
          E: "positive",
          c: "positive",
          e: "positive",
          N: "positive",
          S: "positive",
          Cw: "positive",
          Kpa: "positive",
          Jsa: "positive",
          k: "positive",
          Fya: "positive",
          Jka: "positive",
          Jkb: "positive",
        },
      ),
      cell(
        "7",
        {
          ...baseNegative,
          c: "positive",
          e: "positive",
          M: "positive",
          s: "positive",
          V: "positive",
          Jsb: "positive",
          Lea: "positive",
          k: "positive",
          Fya: "positive",
          Fyb: "positive",
          Jka: "positive",
        },
      ),
      cell(
        "8",
        {
          ...baseNegative,
          c: "positive",
          e: "positive",
          N: "positive",
          S: "positive",
          Kpb: "positive",
          Lub: "positive",
          P1: "positive",
          k: "positive",
          Fyb: "positive",
          Jkb: "positive",
        },
      ),
      cell(
        "9",
        {
          ...baseNegative,
          c: "positive",
          e: "positive",
          M: "positive",
          N: "positive",
          s: "positive",
          Cw: "positive",
          Kpa: "positive",
          Jsa: "positive",
          K: "positive",
          k: "positive",
          Fya: "positive",
          Fyb: "positive",
        },
      ),
      cell(
        "10",
        {
          ...baseNegative,
          C: "positive",
          c: "positive",
          e: "positive",
          S: "positive",
          s: "positive",
          V: "positive",
          Lua: "positive",
          P1: "positive",
          Leb: "positive",
          k: "positive",
          Jka: "positive",
        },
      ),
      cell(
        "11",
        {
          ...baseNegative,
          D: "positive",
          E: "positive",
          c: "positive",
          M: "positive",
          N: "positive",
          Cw: "positive",
          Jsb: "positive",
          Lea: "positive",
          k: "positive",
          Fya: "positive",
          Fyb: "positive",
          Jkb: "positive",
        },
      ),
      autoControl,
    ],
    reactions: {
      "cell-1": "2+",
      "cell-2": "0",
      "cell-3": "0",
      "cell-4": "2+",
      "cell-5": "0",
      "cell-6": "2+",
      "cell-7": "2+",
      "cell-8": "0",
      "cell-9": "2+",
      "cell-10": "0",
      "cell-11": "2+",
      auto: "0",
    },
  },
  {
    id: "case-anti-d",
    title: "Case 3",
    summary: "Synthetic panel with IAT reactivity consistent with anti-D.",
    targetAntibodyId: "anti-D",
    cells: [
      cell(
        "1",
        {
          ...baseNegative,
          D: "positive",
          C: "positive",
          e: "positive",
          M: "positive",
          S: "positive",
          Cw: "positive",
          Kpb: "positive",
          Lua: "positive",
          k: "positive",
          Fya: "positive",
          Jka: "positive",
        },
      ),
      cell(
        "2",
        {
          ...baseNegative,
          D: "positive",
          C: "positive",
          e: "positive",
          N: "positive",
          s: "positive",
          V: "positive",
          Kpa: "positive",
          Jsb: "positive",
          P1: "positive",
          k: "positive",
          Fyb: "positive",
          Jkb: "positive",
        },
      ),
      cell(
        "3",
        {
          ...baseNegative,
          D: "positive",
          E: "positive",
          c: "positive",
          M: "positive",
          N: "positive",
          Cw: "positive",
          Jsa: "positive",
          K: "positive",
          k: "positive",
          Jka: "positive",
        },
      ),
      cell(
        "4",
        {
          ...baseNegative,
          E: "positive",
          c: "positive",
          e: "positive",
          S: "positive",
          s: "positive",
          Kpb: "positive",
          Lub: "positive",
          Lea: "positive",
          k: "positive",
          Fya: "positive",
        },
      ),
      cell(
        "5",
        {
          ...baseNegative,
          c: "positive",
          e: "positive",
          M: "positive",
          P1: "positive",
          V: "positive",
          Lua: "positive",
          Leb: "positive",
          k: "positive",
          Fyb: "positive",
          Jkb: "positive",
        },
      ),
      cell(
        "6",
        {
          ...baseNegative,
          E: "positive",
          c: "positive",
          e: "positive",
          N: "positive",
          S: "positive",
          Cw: "positive",
          Kpa: "positive",
          Jsa: "positive",
          k: "positive",
          Fya: "positive",
          Jka: "positive",
          Jkb: "positive",
        },
      ),
      cell(
        "7",
        {
          ...baseNegative,
          c: "positive",
          e: "positive",
          M: "positive",
          s: "positive",
          V: "positive",
          Jsb: "positive",
          Lea: "positive",
          k: "positive",
          Fya: "positive",
          Jka: "positive",
        },
      ),
      cell(
        "8",
        {
          ...baseNegative,
          c: "positive",
          e: "positive",
          N: "positive",
          S: "positive",
          Kpb: "positive",
          Lub: "positive",
          P1: "positive",
          k: "positive",
          Fyb: "positive",
          Jkb: "positive",
        },
      ),
      cell(
        "9",
        {
          ...baseNegative,
          c: "positive",
          e: "positive",
          M: "positive",
          N: "positive",
          s: "positive",
          Cw: "positive",
          Kpa: "positive",
          Jsa: "positive",
          K: "positive",
          k: "positive",
          Fya: "positive",
          Fyb: "positive",
        },
      ),
      cell(
        "10",
        {
          ...baseNegative,
          C: "positive",
          c: "positive",
          e: "positive",
          S: "positive",
          s: "positive",
          V: "positive",
          Lua: "positive",
          P1: "positive",
          Leb: "positive",
          k: "positive",
          Jka: "positive",
        },
      ),
      cell(
        "11",
        {
          ...baseNegative,
          D: "positive",
          E: "positive",
          c: "positive",
          M: "positive",
          N: "positive",
          Cw: "positive",
          Jsb: "positive",
          Lea: "positive",
          k: "positive",
          Fyb: "positive",
          Jkb: "positive",
        },
      ),
      autoControl,
    ],
    reactions: {
      "cell-1": "2+",
      "cell-2": "2+",
      "cell-3": "2+",
      "cell-4": "0",
      "cell-5": "0",
      "cell-6": "0",
      "cell-7": "0",
      "cell-8": "0",
      "cell-9": "0",
      "cell-10": "0",
      "cell-11": "2+",
      auto: "0",
    },
  },
  {
    id: "case-anti-jkb",
    title: "Case 4",
    summary: "Synthetic panel with IAT reactivity consistent with anti-Jkb.",
    targetAntibodyId: "anti-Jkb",
    cells: [
      cell(
        "1",
        {
          ...baseNegative,
          D: "positive",
          C: "positive",
          e: "positive",
          M: "positive",
          S: "positive",
          Cw: "positive",
          Kpb: "positive",
          Lua: "positive",
          k: "positive",
          Fya: "positive",
          Jka: "positive",
        },
      ),
      cell(
        "2",
        {
          ...baseNegative,
          D: "positive",
          C: "positive",
          e: "positive",
          N: "positive",
          s: "positive",
          V: "positive",
          Kpa: "positive",
          Jsb: "positive",
          P1: "positive",
          k: "positive",
          Fyb: "positive",
          Jka: "positive",
          Jkb: "positive",
        },
      ),
      cell(
        "3",
        {
          ...baseNegative,
          D: "positive",
          E: "positive",
          c: "positive",
          M: "positive",
          N: "positive",
          Cw: "positive",
          Jsa: "positive",
          K: "positive",
          k: "positive",
          Jka: "positive",
        },
      ),
      cell(
        "4",
        {
          ...baseNegative,
          E: "positive",
          c: "positive",
          e: "positive",
          S: "positive",
          s: "positive",
          Kpb: "positive",
          Lub: "positive",
          Lea: "positive",
          k: "positive",
          Fya: "positive",
        },
      ),
      cell(
        "5",
        {
          ...baseNegative,
          c: "positive",
          e: "positive",
          M: "positive",
          P1: "positive",
          V: "positive",
          Lua: "positive",
          Leb: "positive",
          k: "positive",
          Fyb: "positive",
          Jkb: "positive",
        },
      ),
      cell(
        "6",
        {
          ...baseNegative,
          E: "positive",
          c: "positive",
          e: "positive",
          N: "positive",
          S: "positive",
          Cw: "positive",
          Kpa: "positive",
          Jsa: "positive",
          k: "positive",
          Fya: "positive",
          Jka: "positive",
          Jkb: "positive",
        },
      ),
      cell(
        "7",
        {
          ...baseNegative,
          c: "positive",
          e: "positive",
          M: "positive",
          s: "positive",
          V: "positive",
          Jsb: "positive",
          Lea: "positive",
          k: "positive",
          Fya: "positive",
          Jka: "positive",
        },
      ),
      cell(
        "8",
        {
          ...baseNegative,
          c: "positive",
          e: "positive",
          N: "positive",
          S: "positive",
          Kpb: "positive",
          Lub: "positive",
          P1: "positive",
          k: "positive",
          Fyb: "positive",
          Jkb: "positive",
          Jka: "positive",
        },
      ),
      cell(
        "9",
        {
          ...baseNegative,
          c: "positive",
          e: "positive",
          M: "positive",
          N: "positive",
          s: "positive",
          Cw: "positive",
          Kpa: "positive",
          Jsa: "positive",
          K: "positive",
          k: "positive",
          Fya: "positive",
          Fyb: "positive",
        },
      ),
      cell(
        "10",
        {
          ...baseNegative,
          C: "positive",
          c: "positive",
          e: "positive",
          S: "positive",
          s: "positive",
          V: "positive",
          Lua: "positive",
          P1: "positive",
          Leb: "positive",
          k: "positive",
          Jka: "positive",
        },
      ),
      cell(
        "11",
        {
          ...baseNegative,
          D: "positive",
          E: "positive",
          c: "positive",
          M: "positive",
          N: "positive",
          Cw: "positive",
          Jsb: "positive",
          Lea: "positive",
          k: "positive",
          Fyb: "positive",
          Jkb: "positive",
          Jka: "positive",
        },
      ),
      autoControl,
    ],
    reactions: {
      "cell-1": "0",
      "cell-2": "2+",
      "cell-3": "0",
      "cell-4": "0",
      "cell-5": "2+",
      "cell-6": "2+",
      "cell-7": "0",
      "cell-8": "2+",
      "cell-9": "0",
      "cell-10": "0",
      "cell-11": "2+",
      auto: "0",
    },
  },
];
