services:
  app:
    image: ${ANTIBODY_IDENTIFICATION_IMAGE}
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      PORT: "3005"
    networks:
      - app
      - ingress
    labels:
      - traefik.enable=true
      - traefik.docker.network=infra_ingress
      - traefik.http.routers.antibodyidentification.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
      - traefik.http.routers.antibodyidentification.entrypoints=websecure
      - traefik.http.routers.antibodyidentification.tls.certresolver=letsencrypt
      - traefik.http.services.antibodyidentification.loadbalancer.server.port=${PORT}

networks:
  ingress:
    external: true
    name: infra_ingress
  app:
    driver: bridge
